### ISSUE TITLE
[Feature] Remove all modal prompts

### ISSUE THREAD

**Issue by jjcodestuff** [derekhe/msfs2020-map-enhancement#290] opened 2022-11-10 01:30 UTC
#### Motivation

It is not an optimal user experience to have to confirm things via modals within this application. 

#### Detailed design

**Problem 1:** "_The sim is already started..._" warning modal.

This warning should be removed or changed. The only options are "Quit Map enhancement" or "Cancel", this isn't intuitive and its annoying. Sometimes you have to restart the app and it doesn't make sense since the application works just fine if you start it after MSFS. 

**Problem 2:** "_Mod is running confirm close_?" modal. A lot of MSFS users use applications like MSFS Addons Linker to start and stop applications when FlightSimulator.exe is running. With this modal being forced on users, we can't quit the application and it stays running, this is annoying. 

Thanks!

**Comment by derekhe** [comment] 2022-11-10 13:04
Thanks for your feedback:

For Problem 1: 
The app MUST start before you start MSFS, many issues were reported but the root cause is they start MSFS2020 first.

For Problem 2:
People has reported that they sometimes close this app by mistake which is very bad when they are flying (and start the app again, the map injection will fail). So I add this to ask confirmation.

If you have more ideas how to solve the problem, please discuss here :)

**Comment by jjcodestuff** [comment] 2022-11-17 01:45
@derekhe the solution for problem 2 would be to either:

a) Reimplement the feature from the previous version where you could minimize the application to the system tray, or 
b) Add a Yes/No boolean in the settings `Force Confirmation to Close MSFS Map Enhancement?:  ☐`

**Closed** 2022-12-05 12:13 UTC
Labels: feature
