### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by airfede78** [derekhe/msfs2020-map-enhancement#396] opened 2023-05-16 10:45 UTC
I can't start from GOOGLE MAPS SERVER as I receive this message:

Unable to access remote image server

If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.
If you are using a proxy to connect to the remote server, please ensure that the proxy is working.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.

**Comment by derekhe** [comment] 2023-05-16 10:59
Did you check all the things I mentioned?

**Comment by DenisFerrari74** [comment] 2023-05-16 12:23
Same problem here.

Checked FAQ. no proxy, all normal and - in my case - during last weekend this 7.1.6. version was running without any issue using Google Maps Server (one I always use).

**Comment by Pasty69** [comment] 2023-05-16 14:16
> same problem here. Yesterday was all ok

The problem seems resolved. Maybe a temporary down of some google servers?

**Comment by airfede78** [comment] 2023-05-16 14:26
I still have the problem, I'm trying now but doesn't work...

________________________________
Da: Pasty69 ***@***.***>
Inviato: Martedì 16 Maggio 2023, 16:17
A: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: airfede78 ***@***.***>; Author ***@***.***>
Oggetto: Re: [derekhe/msfs2020-map-enhancement] Image server test failed (Issue #396)


same problem here. Yesterday was all ok

The problem seems resolved. Maybe a temporary down of some google servers?

**Comment by DenisFerrari74** [comment] 2023-05-16 14:52
Still not solved here too.

**Comment by mhadjih2** [comment] 2023-05-16 15:52
Same here... Nothing changed in setp, but no connection today to Google Maps

**Comment by boeing186** [comment] 2023-05-16 15:59
Same here. Was working last week with 7.1.6

**Comment by dibraze** [comment] 2023-05-16 17:00
same here in Central Europe

**Comment by Eldad10G** [comment] 2023-05-16 17:12
Same problem in Israel since this morning after it worked will yesterday. Latest 7.1.6 version, updated Windows 11, OpenXR. Configuration did not change from yesterday.

**Comment by Mzhmoud1986** [comment] 2023-05-16 17:35
me too i have the same problem

**Comment by Ericmao666** [comment] 2023-05-16 18:45
Still not solved here too. please try to solve it ~~  

many thanks

**Comment by leandroarndt** [comment] 2023-05-16 19:09
Same here (and the mod keeps adding lines to the hosts file every time I try to start it). https://www.google.com/maps works fine, including the satellite images.

I can't find any file at %appdata%\msfs2020-map-enhancement\logs

This is my first try of the application, and a very unpleasant one.

**Comment by Eldad10G** [comment] 2023-05-16 19:26
My apology to the developer for not mentioning this earlier, but for me this is the best add-on to MSFS 2020! I highly recommend it and would love to also have it in X-Plane.
So Derek, thanks a lot for this excellent software and let me know how I can help resolve the problem (if you need more data on my configuration).

**Comment by StevenSilvaB767** [comment] 2023-05-16 20:05
I don't know if the problem is the same but when I start the application and select Google Maps everything works but when I am already inside the sim at the airport to select the gate the image looks like FS9 and when I load the flight it tells me that my bandwidth is low

MSFS MAp Enhancement 7.1.6

MSFS 1.33.3.0 (BETA)

**Comment by steffensen22567** [comment] 2023-05-16 21:41
Same issue here. Worked great two days ago now pffft. I can get to Google maps with no issue. No proxy and it seems this question isn't frequent enough. I cleared my cache using the application settings. No love. Just adding to the noise. This is a fantastic tool and I hope this can be resolved.

**Comment by LowRiffer** [comment] 2023-05-16 22:42
Having the same issue. Have also tried everything on this post and have referenced the FAQ. No luck.  What's the dealio, looks like no one knows....bummer.

**Comment by Aseinsha** [comment] 2023-05-16 22:51
having same issue, yesterday was working fine, nothing changed. All other sources work fine (pro user) but anything that connects to google fails. I'm in US and no issues with google services.

**Comment by tijeanguizou** [comment] 2023-05-17 00:10
Same issue here. Worked just fine yesterday. Now it doesn't.  By the way this is an awesome app!

**Comment by daNTEEEEEEE** [comment] 2023-05-17 00:23
Same issue, just bought Pro yesterday i hope this can be patched soon.

**Comment by eydrianf** [comment] 2023-05-17 01:59
damn i though i was alone, google maps no longer works, but bing latest does, but it sucks caused it outdated in my country... anyone else have found a fix?

**Comment by eydrianf** [comment] 2023-05-17 01:59
Hi Derek, could this be an issue be looked into?

**Comment by klem56** [comment] 2023-05-17 05:50
We just had a Windows update but I'm fairly sure it was working after that.

**Comment by Jan3377** [comment] 2023-05-17 06:22
Same problem here in the Czech Republic (Cenral Europe). I even purchased a Pro license but it is good for nothing. The server seems to be down since yesterdy.

**Comment by Nathan-Shea** [comment] 2023-05-17 07:47
Seems to be a problem here as well (only with google maps free). I tried no VPN and a VPN in multiple countries (it's worked with and without the VPN before). I couldn't find any local logs but grabbed this on its way to your server.


```{"Timestamp":"2023-05-17T07:18:38.0174982Z","Level":"Error","MessageTemplate":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","RenderedMessage":"Connection id \"\"0HMQMK37GTR6H\"\", Request id \"\"0HMQMK37GTR6H:0000000B\"\": An unhandled exception was thrown by the application.","Exception":"System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).\r\n   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at core.ImageServer.ImageLoader.LoadOriginalImage(String quadKey, MapSource mapSource) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 177\r\n   at core.ImageServer.ImageLoader.LoadNormalLod(MapSource mapSource, String quadKey, Boolean cacheEnabled) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 82\r\n   at core.ImageServer.ImageLoader.LoadImage(MapSource mapSource, String quadKey, Boolean cacheEnabled) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 232\r\n   at core.ImageServer.ImageRequestHandler.ImageHandler(HttpContext context, String path) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageRequestHandler.cs:line 74\r\n   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at core.ImageServer.ImageServer.ColorCorrectionFilter(HttpContext context, RequestDelegate next) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageServer.cs:line 147\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","Properties"```

My Device ID if you are interested ` XFQN3Y3KDPC9SK32RTV2SP1ABF5140T19MG3TRHGXCR01KJTP920 `

**Comment by derekhe** [comment] 2023-05-17 07:48
Thanks for reporting, I am checking the issue&nbsp;





------------------ Original ------------------
From: Nathan Shea ***@***.***&gt;
Date: Wed,May 17,2023 3:47 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Image server test failed(Issue #396)





 
Seems to be a problem here as well (only with google maps free). I tried no VPN and a VPN in multiple countries (it's worked with and without the VPN before). I couldn't find any local logs but grabbed this on its way to your server.
 
{"Timestamp":"2023-05-17T07:18:38.0174982Z","Level":"Error","MessageTemplate":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","RenderedMessage":"Connection id \"\"0HMQMK37GTR6H\"\", Request id \"\"0HMQMK37GTR6H:0000000B\"\": An unhandled exception was thrown by the application.","Exception":"System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).\r\n   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at core.ImageServer.ImageLoader.LoadOriginalImage(String quadKey, MapSource mapSource) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 177\r\n   at core.ImageServer.ImageLoader.LoadNormalLod(MapSource mapSource, String quadKey, Boolean cacheEnabled) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 82\r\n   at core.ImageServer.ImageLoader.LoadImage(MapSource mapSource, String quadKey, Boolean cacheEnabled) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageLoader.cs:line 232\r\n   at core.ImageServer.ImageRequestHandler.ImageHandler(HttpContext context, String path) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageRequestHandler.cs:line 74\r\n   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke&gt;g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at core.ImageServer.ImageServer.ColorCorrectionFilter(HttpContext context, RequestDelegate next) in D:\\dev\\msfs2020-map-enhancement-dotnet\\electron-ui\\core\\ImageServer\\ImageServer.cs:line 147\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","Properties"
 
My Device ID if you are interested XFQN3Y3KDPC9SK32RTV2SP1ABF5140T19MG3TRHGXCR01KJTP920

**Comment by derekhe** [comment] 2023-05-17 13:43
Fixed in this version: https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.7

**Closed by derekhe** 2023-05-17 13:43 UTC

**Comment by airfede78** [comment] 2023-05-17 14:49
Thank you so much! ✈️

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eldad10G** [comment] 2023-05-17 16:06
The new version 7.1.7 works well! Thank you for the prompt fix and response!

**Comment by bledo22** [comment] 2023-05-17 16:32
Thank you form the extremely quick response... In just 24 hours the issue was solved. It was really annoying though, because this mod is so essential, it improves MSFS so much, that paying without it was not a good experiencie.
Keep up the good work!

**Comment by Ericmao666** [comment] 2023-05-17 18:33
thanks for the prompt response and now it's working smoothly and well. 

cheers!

**Comment by steffensen22567** [comment] 2023-05-17 22:56
Works great! Thank you for the awesome and prompt response to correct the issue! Awesome job!
