### ISSUE TITLE
Bug with rendering or MSFS mesh overlapping?

### ISSUE THREAD

**Issue by natementer** [derekhe/msfs2020-map-enhancement#794] opened 2024-12-06 17:08 UTC
**Describe the bug**

Bing maps looks correct from a distance but when zooming in to some airports, the old, incorrect runway meshes load in. Everything else is working because i can tell that the scenery outside the airport has changed.

**MSFS version:**
 - msstore
 - MSFS2024 Version 1.1.10.0

**Mod version:**
- 8.0.29

**Device ID**
- 9HG73SY4FRY6ZZZD2NJRBGPWM5GHQW64WD184D9YBMGP11PY1S8G

**Screenshots**
![Screenshot 2024-12-06 112849](https://github.com/user-attachments/assets/41124778-eaa0-4551-96ce-ea3696359f91)
Sorry its very bright windows did that automatically, however it shows that the map features the correct runway layouts within a year or so. This is Willow run airport in Ypsilanti, Michigan, U.S. 
![Screenshot 2024-12-06 112915](https://github.com/user-attachments/assets/445203d4-cb7f-4d34-9959-4360d7c7e7a6)
This is when zoomed in slightly more and you can vaguely tell, from that SS, that the meshes of the RW are not what is shown on the map. Still Willow Run
![Screenshot 2024-12-06 112953](https://github.com/user-attachments/assets/68c6d61a-6690-4034-b6d9-4c955a8b0f02)
This is Detroit airport, with the same problem as Willow Run. This is the correct layout featured on the map.
![Screenshot 2024-12-06 113007](https://github.com/user-attachments/assets/46c0c479-a56e-48ae-b7e6-ac63b095a257)
However zooming in reveals an active runway covered in dirt.

**Additional context**
I have deleted hosts files and cache and turned off photogrammetry without being able to get rid of these meshes. Any help is appreciated,

EDIT TO ADD: this happens on google maps as well as bing maps.

**Comment by derekhe** [comment] 2024-12-07 05:39
I tried the place you mentioned and don't know where's the problem coming from.
The very bright screen capture is caused by the HDR option, you can turn it off. Could you also capture the images again and point out the problem?

**Comment by natementer** [comment] 2024-12-07 18:50
KDTW Coords: 42°12'52"N 83°20'22"W
KYIP coords: 42°14'06"N 83°31'41"W
I turned the HDR off and got some more screenshots with some labels. However i was unable to get the maps to work correctly due to some mod installations after using the map enhancer. I also have some time constraints preventing me from ironing that out at the moment. But the problem i seem to have, in my very humble opinion, is that either the map enhancer utilizes the same runway textures/meshes as MSFS 24 or MSFS 24 overrides the map enhancers runways. I say this because when I was able to get the map enhancer to work, the scenery around some airports (like KYIP) had changed to be more recent, but the runway layout was still quite dated and looked very similar, if not identical to MSFS 24 Map. Anyhow, here are the screenshots:

**_KYIP:_**
KYIP EFB image (about correct for the current date) Labels highlight differences in the layouts
![WillowRunEFB](https://github.com/user-attachments/assets/e6b9c480-dfa4-4128-9407-9087ef628012)
KYIP Free Flight/In Game image/scenery:
![KYIPfreeflight](https://github.com/user-attachments/assets/ec875baf-fb61-4076-b342-b4ed95a32357)
Google Earth image of KYIP showing approx. last time the runway in the game was used in real life. (over 10 years!)

**_KDTW:_**
KDTW EFB Image (correct for current date): 
![DTWEFB](https://github.com/user-attachments/assets/7df51999-96f8-4bf5-a75b-ce94149f10ac)
![KDTWfreeflight](https://github.com/user-attachments/assets/05928a7f-5b08-4d0a-bf7f-dd8eb984d83d)

I was unable to zoom further in for KDTW because a mod installed for it would change the runway layout when zoomed further in/on the ground. 
Hope this helps!!

**Comment by derekhe** [comment] 2024-12-08 01:30
I see. Thanks for the explanation. The rendered runway should be generated from outdated data. The EFB screen shows the satellite images coming from my mod. We had to use 3rd party plugins or airports mod to fix this which are out of scope of this mod. Hope MSFS can provide the correct data.

**Closed** 2024-12-11 11:12 UTC
